name: Bug Report
description: File a simple bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      placeholder: ex. email@example.com
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the error.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser?
      options:
        - Firefox
        - Chrome
        - Safari
        - Edge
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
